"""Standalone documentation feature — annotates legacy Fortran with
Doxygen-style ``!>`` docstrings and (optionally) generates a self-contained
Sphinx site for the codebase.

Two operating modes:

- **Inline** (default) — rewrites the Fortran sources in place, adding a
  ``!> @brief`` / ``!> @details`` / ``!> @param`` block above each
  ``subroutine`` / ``function``. Idempotent: existing blocks generated by
  this tool are detected by the ``!> @generated_by fortranspire`` marker
  and replaced rather than duplicated.
- **Sphinx site** (``--sphinx`` or ``--site-only``) — emits a
  ``documentation/<codebase>/`` directory with ``conf.py``, ``index.rst``
  and one ``.rst`` per Fortran file, ready for ``sphinx-build``.

Each routine is documented at **two levels** in a single LLM call:

- ``short_summary`` (≤1 line) — stakeholder view.
- ``detailed`` (2–4 sentences) — developer view: INTENT semantics,
  invariants, gotchas (hidden ``SAVE``, ``COMMON`` blocks, index ordering).

``--no-llm`` keeps everything signature-only (Loki extraction only): useful
for offline runs and for verifying the pipeline plumbing without burning
tokens.
"""
from __future__ import annotations

import argparse
import contextlib
import io
import json
import re
import sys
import textwrap
from dataclasses import dataclass, field
from hashlib import sha1
from pathlib import Path
from typing import Any, Iterable

from fortranspire.agent.translation_graph_phase1 import parser_phase1

GENERATED_MARKER = "!> @generated_by fortranspire"
SCHEMA_VERSION = 1   # bump if the inline docstring format changes


# ── Data classes ────────────────────────────────────────────────────────────

@dataclass
class RoutineDoc:
    name: str
    kind: str               # "subroutine" or "function"
    line: int               # 1-based line of the `subroutine` / `function` keyword
    arguments: list[str]
    intent_map: dict[str, str]
    has_io: bool
    has_save: bool
    body_hash: str          # to skip LLM re-runs when nothing changed
    source: str = ""        # raw Fortran source of the routine (for the Sphinx toggle)
    short_summary: str = "(undocumented)"
    detailed: str = "(no detailed description available)"
    params: dict[str, str] = field(default_factory=dict)


@dataclass
class FileDoc:
    file: str
    routines: list[RoutineDoc]
    parse_error: str | None = None


# ── Loki-driven extraction ──────────────────────────────────────────────────

_ROUTINE_DECL_RE = re.compile(
    # `[ \t]*` (not `\s*`) — `\s` includes `\n`, which would let the match
    # start on a preceding blank line and yield the wrong line number.
    r"^[ \t]*(subroutine|function)\s+(\w+)", re.IGNORECASE | re.MULTILINE,
)


def _routine_line(source: str, name: str) -> tuple[int, str]:
    """Return (1-based line, kind) of the routine declaration. Falls back to (1, 'subroutine')."""
    for match in _ROUTINE_DECL_RE.finditer(source):
        if match.group(2).lower() == name.lower():
            kind = match.group(1).lower()
            line = source.count("\n", 0, match.start()) + 1
            return line, kind
    return 1, "subroutine"


def extract_routines(path: str) -> FileDoc:
    """Run the deterministic Loki stage on `path` and return per-routine metadata."""
    abspath = str(Path(path).resolve())
    source = Path(abspath).read_text(encoding="utf-8")

    state: dict[str, Any] = {
        "fortran_filepath": abspath,
        "fortran_code": source,
        "ast_info": {},
        "kernel_results": [],
        "schema": {},
        "is_program": False,
        "executed_agents": [],
    }
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        try:
            out = parser_phase1(state)
        except Exception as exc:
            return FileDoc(file=abspath, routines=[], parse_error=str(exc))

    if (out.get("ast_info") or {}).get("status") == "error":
        return FileDoc(file=abspath, routines=[], parse_error=out["ast_info"].get("message"))

    routines: list[RoutineDoc] = []
    for kernel in out.get("kernel_results", []) or []:
        name = kernel.get("routine_name", "?")
        line, kind = _routine_line(source, name)
        body = kernel.get("fortran_code", "")
        intent_map: dict[str, str] = dict(kernel.get("intent_map") or {})
        routines.append(RoutineDoc(
            name=name,
            kind=kind,
            line=line,
            arguments=list(intent_map.keys()),
            intent_map=intent_map,
            has_io=bool(kernel.get("has_io")),
            has_save=bool(kernel.get("has_save")),
            body_hash=sha1(body.encode("utf-8")).hexdigest()[:12],
            source=body,
        ))
    return FileDoc(file=abspath, routines=routines)


# ── LLM narrative generation ────────────────────────────────────────────────

def _get_system_prompt() -> str:
    """Lazy — only loaded when the LLM actually fires (keeps --no-llm cheap)."""
    from fortranspire.prompts.loader import load_prompt
    return load_prompt("doc_routine", version="v1")

_RESPONSE_SCHEMA_HINT = textwrap.dedent("""\
    Reply with a JSON object matching exactly this schema:
    {
      "short_summary": "<= 100 chars, single sentence, no period at end",
      "detailed":      "2 to 4 sentences, plain text, no Markdown",
      "params": {"<arg_name>": "physical meaning + role + units when obvious"}
    }
""")


def _fortls_context(workspace: str | None, routine_name: str) -> str:
    """Best-effort enrichment via the Fortran Language Server.

    Returns a short list of neighbouring symbols (other routines / modules
    in the same file) so the LLM has structural context beyond the body
    it's documenting. Silently returns `""` when fortls is missing or
    workspace can't be probed — keeps the documenter usable without the
    `[gpu]` extra installed.
    """
    if not workspace:
        return ""
    try:
        from fortranspire.agent.fortls_oracle import summarize_context
        return summarize_context(workspace, routine_name)
    except Exception:
        return ""


def _build_user_prompt(
    routine: RoutineDoc,
    body: str,
    *,
    workspace: str | None = None,
) -> str:
    flags = []
    if routine.has_io:    flags.append("contains I/O (PRINT/WRITE/READ)")
    if routine.has_save:  flags.append("uses SAVE — hidden state across calls")
    flag_line = ("\nKnown traits: " + "; ".join(flags) + ".") if flags else ""
    args_line = ", ".join(f"{a}({routine.intent_map.get(a, '?')})"
                          for a in routine.arguments) or "(no arguments)"
    truncated = body if len(body) < 4000 else body[:4000] + "\n... [truncated]"

    # Optional fortls oracle context — appears as an extra block so the
    # LLM can use it without re-parsing the source itself.
    fortls_block = _fortls_context(workspace, routine.name)
    fortls_section = f"\n{fortls_block}\n" if fortls_block else ""

    return (
        f"Routine: {routine.kind.upper()} {routine.name}\n"
        f"Arguments: {args_line}{flag_line}{fortls_section}\n\n"
        "Source:\n```fortran\n"
        f"{truncated}\n```\n\n"
        f"{_RESPONSE_SCHEMA_HINT}"
    )


def _parse_llm_json(blob: str) -> dict | None:
    """Best-effort JSON extraction — handles ```json fences and stray prose."""
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", blob, re.DOTALL)
    if fenced:
        candidate = fenced.group(1)
    else:
        match = re.search(r"\{.*\}", blob, re.DOTALL)
        candidate = match.group(0) if match else blob
    try:
        return json.loads(candidate)
    except json.JSONDecodeError:
        return None


def generate_narrative(
    routine: RoutineDoc,
    body: str,
    *,
    workspace: str | None = None,
) -> None:
    """Populate ``routine.short_summary`` / ``detailed`` / ``params`` via the LLM.

    Uses ``llm.with_structured_output(DocRoutineOutput)`` so the model returns
    a typed Pydantic object directly — no regex parsing of the response.
    Falls back to the legacy regex JSON parser if the structured call raises
    (some self-hosted backends don't yet implement function/JSON-schema mode).

    When ``workspace`` is provided and `fortls` is on PATH, the prompt is
    enriched with neighbouring-symbol context fetched from the Fortran
    Language Server — grounds the narrative and reduces hallucinations
    about names/relationships in the surrounding module.

    Lazy-imports the LLM stack so ``--no-llm`` runs don't need any langchain deps.
    """
    from langchain_core.messages import HumanMessage, SystemMessage

    from fortranspire.agent.schemas import DocRoutineOutput
    from fortranspire.llm import get_llm

    llm = get_llm("code")  # Codestral handles narrative-from-code well, cheaper than Mistral-Large
    messages = [
        SystemMessage(content=_get_system_prompt()),
        HumanMessage(content=_build_user_prompt(routine, body, workspace=workspace)),
    ]

    result: DocRoutineOutput | None = None
    try:
        result = llm.with_structured_output(DocRoutineOutput).invoke(messages)
    except Exception:
        # Self-hosted vLLM / TGI without JSON-schema support → fall back to
        # the legacy regex JSON parser. Same prompt, looser validation.
        response = llm.invoke(messages)
        raw = response.content if hasattr(response, "content") else str(response)
        parsed = _parse_llm_json(raw)
        if parsed:
            try:
                result = DocRoutineOutput(**parsed)
            except Exception:
                return  # malformed beyond recovery — keep defaults

    if result is None:
        return

    short = (result.short_summary or "").strip()
    detailed = (result.detailed or "").strip()
    if short:    routine.short_summary = short[:160]
    if detailed: routine.detailed = detailed
    routine.params = {
        str(k): str(v).strip() for k, v in (result.params or {}).items() if v
    }


# ── Inline docstring injection (idempotent) ─────────────────────────────────

def _docstring_block(routine: RoutineDoc) -> str:
    """Render the Doxygen-style `!>` block for one routine."""
    lines: list[str] = [
        f"{GENERATED_MARKER} v{SCHEMA_VERSION} routine={routine.name} body={routine.body_hash}",
        f"!> @brief   {routine.short_summary}",
    ]
    # Wrap the detailed paragraph at 88 cols, prefixed with `!>`.
    detailed_lines = textwrap.wrap(routine.detailed, width=84) or ["(no description)"]
    lines.append(f"!> @details {detailed_lines[0]}")
    for cont in detailed_lines[1:]:
        lines.append(f"!>          {cont}")
    for arg in routine.arguments:
        intent = routine.intent_map.get(arg, "in")
        doc = routine.params.get(arg, "(undocumented)")
        lines.append(f"!> @param[{intent.lower()}] {arg}  {doc}")
    if routine.has_save:
        lines.append("!> @warning  uses SAVE — keeps hidden state between calls.")
    if routine.has_io:
        lines.append("!> @warning  contains I/O — blocks GPU port (FORT001).")
    return "\n".join(lines) + "\n"


_EXISTING_BLOCK_RE = re.compile(
    r"^(?:!>\s.*\n)*?!>\s@generated_by\sfortranspire.*\n(?:!>\s.*\n)*",
    re.MULTILINE,
)


def _strip_existing_block_above(source: str, line_no: int) -> tuple[str, int]:
    """If the lines immediately above ``line_no`` are a previous fortranspire block,
    remove them. Returns (new_source, new_line_no)."""
    lines = source.splitlines(keepends=True)
    idx = line_no - 1  # 0-based index of the routine declaration line
    # Walk upward over contiguous `!>` lines.
    start = idx
    while start > 0 and lines[start - 1].lstrip().startswith("!>"):
        start -= 1
    block = "".join(lines[start:idx])
    if GENERATED_MARKER in block:
        new_source = "".join(lines[:start] + lines[idx:])
        return new_source, line_no - (idx - start)
    return source, line_no


def inject_inline_docstrings(file_doc: FileDoc, *, dry_run: bool = False) -> bool:
    """Rewrite the source file in place, inserting one docstring block per routine.
    Returns True if the file was changed (or would be in dry-run mode)."""
    if file_doc.parse_error or not file_doc.routines:
        return False

    source = Path(file_doc.file).read_text(encoding="utf-8")
    # Process routines bottom-up so earlier insertions don't shift later line numbers.
    for routine in sorted(file_doc.routines, key=lambda r: -r.line):
        source, line = _strip_existing_block_above(source, routine.line)
        block = _docstring_block(routine)
        lines = source.splitlines(keepends=True)
        insertion = line - 1
        # Preserve the indentation of the `subroutine`/`function` declaration so the
        # `!>` lines align (cosmetic; gfortran does not care).
        # Same gotcha as the routine-decl regex: `\s` matches `\n`, so a blank
        # `lines[insertion]` (single `\n`) would capture the newline as indent.
        indent = re.match(r"^([ \t]*)", lines[insertion]).group(1) if insertion < len(lines) else ""
        indented_block = "".join(indent + ln if ln.strip() else ln
                                 for ln in block.splitlines(keepends=True))
        lines.insert(insertion, indented_block)
        source = "".join(lines)

    if dry_run:
        sys.stdout.write(source)
        return True

    Path(file_doc.file).write_text(source, encoding="utf-8")
    return True


# ── Sphinx site generation ──────────────────────────────────────────────────

_SPHINX_CONF = '''\
"""Auto-generated by fortranspire — `agent-doc` standalone documentation."""
project   = {project!r}
author    = "fortranspire (https://github.com/maurinl26/fortranspire)"
copyright = "Documentation generated from source — no license claim on the underlying code."

extensions = [
    "myst_parser",
    "sphinx_copybutton",
    "sphinx_design",        # provides the `.. dropdown::` directive used for the source toggle
    "sphinx_togglebutton",  # admonition-based collapse fallback
]
myst_enable_extensions = ["colon_fence", "deflist", "fieldlist"]

html_theme = "furo"
templates_path = ["_templates"]
exclude_patterns = ["_build", ".DS_Store"]
master_doc = "index"
language = "en"

# Make the per-routine collapse-by-default look better.
togglebutton_hint = "Click to show source"
togglebutton_hint_hide = "Click to hide source"
'''

_SPHINX_REQUIREMENTS = """\
sphinx>=7.3,<9
furo>=2024.5
myst-parser>=3.0
sphinx-copybutton>=0.5.2
sphinx-design>=0.6
sphinx-togglebutton>=0.3
"""

_SPHINX_MAKEFILE = """\
SPHINXBUILD ?= sphinx-build
SOURCEDIR   = source
BUILDDIR    = build

html:
\t$(SPHINXBUILD) -b html "$(SOURCEDIR)" "$(BUILDDIR)/html"

clean:
\trm -rf "$(BUILDDIR)"

.PHONY: html clean
"""


def _rst_for_file(file_doc: FileDoc, repo_root: Path) -> str:
    rel = Path(file_doc.file).resolve().relative_to(repo_root) \
        if str(Path(file_doc.file)).startswith(str(repo_root)) else Path(file_doc.file)
    title = str(rel)
    bar = "=" * len(title)
    parts = [title, bar, ""]
    if file_doc.parse_error:
        parts += [f".. warning:: Loki could not parse this file: {file_doc.parse_error}", ""]
        return "\n".join(parts)
    if not file_doc.routines:
        parts.append("*(no routines detected)*")
        return "\n".join(parts)

    for routine in file_doc.routines:
        sig = f"{routine.kind.upper()} {routine.name}"
        parts += [
            sig,
            "-" * len(sig),
            "",
            routine.short_summary + ".",
            "",
            ".. admonition:: Detailed description",
            "",
        ]
        for line in textwrap.wrap(routine.detailed, width=78) or [""]:
            parts.append(f"   {line}")
        parts += ["", "Arguments:", ""]
        if not routine.arguments:
            parts += ["   *(none)*", ""]
        for arg in routine.arguments:
            intent = routine.intent_map.get(arg, "?")
            doc = routine.params.get(arg, "(undocumented)")
            parts.append(f"   * ``{arg}`` *({intent})* — {doc}")
        if routine.has_save:
            parts += ["", ".. warning:: Routine uses ``SAVE`` — hidden state between calls.", ""]
        if routine.has_io:
            parts += ["", ".. warning:: Routine performs I/O — blocks GPU port.", ""]

        # Collapsible source — uses sphinx-design's `dropdown` directive; the
        # generated requirements pull both `sphinx-design` and
        # `sphinx-togglebutton` so either renderer works.
        if routine.source.strip():
            parts += [
                "",
                ".. dropdown:: Show source",
                "   :icon: code",
                "   :animate: fade-in-slide-down",
                "",
                "   .. code-block:: fortran",
                "      :linenos:",
                "",
            ]
            for src_line in routine.source.splitlines():
                parts.append(f"      {src_line}")
            parts.append("")

        parts.append("")

    return "\n".join(parts)


def _safe_rst_basename(file_path: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", Path(file_path).stem)


def generate_sphinx_site(file_docs: list[FileDoc], output_dir: Path, project: str) -> None:
    """Write a self-contained Sphinx project at `output_dir`."""
    source_dir = output_dir / "source"
    (source_dir / "_templates").mkdir(parents=True, exist_ok=True)
    (source_dir / "_static").mkdir(parents=True, exist_ok=True)

    (source_dir / "conf.py").write_text(_SPHINX_CONF.format(project=project), encoding="utf-8")
    (output_dir / "requirements.txt").write_text(_SPHINX_REQUIREMENTS, encoding="utf-8")
    (output_dir / "Makefile").write_text(_SPHINX_MAKEFILE, encoding="utf-8")

    repo_root = Path.cwd().resolve()
    file_pages: list[tuple[str, str]] = []   # (rst basename, file display name)
    for fd in file_docs:
        basename = _safe_rst_basename(fd.file)
        rst_path = source_dir / f"{basename}.rst"
        rst_path.write_text(_rst_for_file(fd, repo_root), encoding="utf-8")
        file_pages.append((basename, str(Path(fd.file).relative_to(repo_root))
                           if str(Path(fd.file)).startswith(str(repo_root)) else fd.file))

    index_parts = [
        project, "=" * len(project), "",
        f"Auto-generated documentation for **{project}** "
        f"({len(file_docs)} file{'s' if len(file_docs) != 1 else ''}, "
        f"{sum(len(fd.routines) for fd in file_docs)} routine"
        f"{'s' if sum(len(fd.routines) for fd in file_docs) != 1 else ''}).",
        "",
        ".. toctree::",
        "   :maxdepth: 2",
        "   :caption: Files",
        "",
    ]
    for basename, _display in sorted(file_pages):
        index_parts.append(f"   {basename}")
    index_parts += ["", "Indices and tables", "==================", "",
                    "* :ref:`genindex`", "* :ref:`search`", ""]
    (source_dir / "index.rst").write_text("\n".join(index_parts), encoding="utf-8")


# ── CLI ─────────────────────────────────────────────────────────────────────

def _walk(paths: Iterable[str]) -> list[str]:
    files: list[str] = []
    for raw in paths:
        p = Path(raw)
        if p.is_dir():
            files.extend(sorted(str(f) for f in p.rglob("*.[fF]90")))
        else:
            files.append(str(p))
    seen = set()
    out = []
    for f in files:
        if f not in seen:
            seen.add(f)
            out.append(f)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="agent-doc",
        description=(
            "Document legacy Fortran 90 code with LLM-generated narratives. "
            "Two modes: inline `!>` Doxygen docstrings (default) and a "
            "self-contained Sphinx site (`--sphinx`, `--site-only`)."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  agent-doc src/seismic.f90                 # inline docstrings, in place\n"
            "  agent-doc --sphinx src/                    # inline + Sphinx site\n"
            "  agent-doc --site-only src/                 # site only, leave sources alone\n"
            "  agent-doc --no-llm src/                    # signatures only, no token cost\n"
            "  agent-doc --dry-run src/kernel.f90         # show what would be inserted\n"
        ),
    )
    parser.add_argument("paths", nargs="+", help="Fortran files or directories to document")
    parser.add_argument("--sphinx", action="store_true",
                        help="In addition to inline docstrings, generate a Sphinx site")
    parser.add_argument("--site-only", action="store_true",
                        help="Generate the Sphinx site only — do not touch source files")
    parser.add_argument("--no-llm", action="store_true",
                        help="Skip LLM calls — use Loki-extracted signatures only")
    parser.add_argument("--project", default=None,
                        help="Project name in the generated Sphinx site (default: derived from path)")
    parser.add_argument("--output", default="documentation",
                        help="Output directory for the Sphinx site (default: documentation/)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print the rewritten source to stdout, do not modify files")
    args = parser.parse_args(argv)

    if args.site_only and args.sphinx:
        parser.error("--site-only implies --sphinx; pass only one of them")
    write_inline = not args.site_only
    write_site = args.sphinx or args.site_only

    files = _walk(args.paths)
    if not files:
        print("agent-doc: no .f90 / .F90 file found in the given paths", file=sys.stderr)
        return 2

    print(f"agent-doc: parsing {len(files)} file(s) with Loki…")
    docs: list[FileDoc] = [extract_routines(f) for f in files]

    total_routines = sum(len(d.routines) for d in docs)
    print(f"agent-doc: {total_routines} routine(s) found across {len(docs)} file(s).")

    if not args.no_llm and total_routines > 0:
        print(f"agent-doc: generating narratives ({total_routines} LLM calls)…")
        for d in docs:
            if d.parse_error:
                continue
            source_text = Path(d.file).read_text(encoding="utf-8")
            workspace = str(Path(d.file).parent)
            for r in d.routines:
                try:
                    generate_narrative(r, source_text, workspace=workspace)
                except Exception as exc:
                    print(f"  ⚠ {Path(d.file).name}::{r.name}  LLM call failed: {exc}",
                          file=sys.stderr)

    changed_files = 0
    if write_inline:
        for d in docs:
            if inject_inline_docstrings(d, dry_run=args.dry_run):
                changed_files += 1
        if not args.dry_run:
            print(f"agent-doc: inline docstrings written into {changed_files} file(s).")

    if write_site:
        project = args.project or Path(args.paths[0]).resolve().name or "fortran-codebase"
        output_dir = Path(args.output) / project
        generate_sphinx_site(docs, output_dir, project)
        print(f"agent-doc: Sphinx site at {output_dir}")
        print(f"  next: cd {output_dir} && pip install -r requirements.txt && make html")

    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
