"""Node 6 — deterministic syntax/compile validation.

Runs `gfortran -fsyntax-only` in two flavours (with and without `!$acc`)
plus `nvfortran -acc` when available. Zero LLM calls.
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import List

from fortranspire.agent.nodes._common import SEP, SEP2, _gpu_compiler, _out, _save
from fortranspire.agent.nodes._state import Phase1State


def _gfortran_local_check(sources: List[Path]) -> tuple[bool, bool, str]:
    """Vérifie la syntaxe Fortran en deux passes avec gfortran.

    Flavor 1 — CPU (sans pragmas) :
        Retire les directives !$acc et compile avec gfortran -O2 -fsyntax-only.
        Valide la logique Fortran pure indépendamment d'OpenACC.

    Flavor 2 — Avec pragmas :
        Compile directement avec gfortran -fopenacc -fsyntax-only.
        Valide que les directives OpenACC sont syntaxiquement correctes.

    Returns:
        (ok_no_acc, ok_with_acc, log)
    """
    gfc = shutil.which("gfortran")
    if not gfc:
        return False, False, "SKIP (gfortran): not found in PATH — brew install gcc"

    logs: List[str] = [f"gfortran: {gfc}"]
    ok_no_acc   = False
    ok_with_acc = False

    def _strip_acc(code: str) -> str:
        return "\n".join(
            line for line in code.splitlines()
            if not re.match(r"^\s*!\$acc", line, re.IGNORECASE)
        )

    def _compile_sequential(srcs: List[Path], flags: List[str], mod_dir: Path,
                             label: str) -> tuple[bool, str]:
        """Compile sources in order: module with -c (produces .mod), then driver with -fsyntax-only."""
        msgs: List[str] = []
        for i, src in enumerate(srcs):
            is_last = (i == len(srcs) - 1)
            # Last source = driver (or single file) → syntax-only; others → compile to get .mod
            if is_last:
                cmd = [gfc] + flags + ["-fsyntax-only", f"-I{mod_dir}", str(src)]
            else:
                cmd = [gfc] + flags + ["-c", f"-J{mod_dir}", f"-I{mod_dir}",
                                       str(src), "-o", str(mod_dir / (src.stem + ".o"))]
            msgs.append(f"  $ {' '.join(cmd)}")
            try:
                r = subprocess.run(cmd, capture_output=True, text=True, timeout=60,
                                   cwd=str(mod_dir))
                if r.returncode != 0:
                    msgs.append(f"  FAIL rc={r.returncode}")
                    msgs.append("  " + (r.stderr or r.stdout)[:600])
                    return False, "\n".join(msgs)
            except Exception as e:
                msgs.append(f"  ERROR: {e}")
                return False, "\n".join(msgs)
        msgs.append(f"  OK — {label}")
        return True, "\n".join(msgs)

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        mod1 = tmp / "mod1"   # .mod files for Flavor 1 (stripped)
        mod2 = tmp / "mod2"   # .mod files for Flavor 2 (with acc)
        mod1.mkdir(); mod2.mkdir()

        # ── Flavor 1 : strip !$acc directives, compile sequentially ──────
        stripped: List[Path] = []
        for src in sources:
            if not src.exists():
                continue
            dst = tmp / ("s_" + src.name)
            dst.write_text(_strip_acc(src.read_text(encoding="utf-8")), encoding="utf-8")
            stripped.append(dst)

        logs.append(f"\nFlavor 1 (CPU, no !$acc):")
        if stripped:
            ok_no_acc, msg = _compile_sequential(stripped, ["-O2"], mod1,
                                                  "Fortran logic is syntactically valid.")
            logs.append(msg)
        else:
            logs.append("  SKIP: no sources")

        # ── Flavor 2 : keep !$acc, use -fopenacc, compile sequentially ───
        orig = [s for s in sources if s.exists()]
        logs.append(f"\nFlavor 2 (with OpenACC, gfortran -fopenacc):")
        if orig:
            ok_with_acc, msg = _compile_sequential(orig, ["-fopenacc"], mod2,
                                                    "OpenACC directives are syntactically valid.")
            logs.append(msg)
        else:
            logs.append("  SKIP: no sources")

    return ok_no_acc, ok_with_acc, "\n".join(logs)

def _make_makefile(out_dir: Path, module_file: str, driver_file: str,
                   binary_name: str, pyx_name: str) -> str:
    """Génère un Makefile pour la compilation GPU + Cython. Toujours produit."""
    return f"""# GPU Fortran + Cython build — generated by agent-gpu
# Usage : make          (compile Fortran GPU)
#         make cython   (build Cython extension)
#         make clean

FC      = nvfortran
FFLAGS  = -acc -gpu=cc80 -Minfo=accel -fast
TARGET  = {binary_name}
MODULE  = fortran_gpu/{module_file}
DRIVER  = fortran_gpu/{driver_file}

all: $(TARGET)

# Compile MODULE first (produces .mod file), then link with DRIVER
$(TARGET): $(MODULE) $(DRIVER)
\t$(FC) $(FFLAGS) -c $(MODULE) -o module_kernels_gpu.o
\t$(FC) $(FFLAGS) $(DRIVER) module_kernels_gpu.o -o $(TARGET)
\t@echo "\\n=== Compiled OK: $(TARGET) ===\\n"
\t@echo "Run with: ./$(TARGET)"

# Cython wrapper (requires Cython + numpy installed)
cython: cython/setup.py
\tcd cython && python setup.py build_ext --inplace
\t@echo "Cython extension built in cython/"

clean:
\trm -f $(TARGET) *.o *.mod

.PHONY: all cython clean
"""


def _make_compile_script(out_dir: Path, module_file: str, driver_file: str,
                          binary_name: str,
                          feature_flags: dict | None = None) -> str:
    """Génère compile_gpu.sh — script autonome portable sur tout nœud GPU (HPC,
    cloud souverain, cluster on-prem)."""
    cpp_flags = ""
    if feature_flags:
        active = [f"-D{k}" for k, v in feature_flags.items() if ".TRUE." in v.upper()]
        if active:
            cpp_flags = " ".join(["-cpp"] + active) + " "
    return f"""#!/bin/bash
# compile_gpu.sh — Compile Fortran GPU kernels with nvfortran (OpenACC)
# Generated by fortranspire gpu. Run this on any GPU node (OpenStack tenant, GENCI, on-prem).
#
# Usage : bash compile_gpu.sh
#         bash compile_gpu.sh --check   (vérifie l'environnement GPU)

set -e

TARGET="{binary_name}"
MODULE="fortran_gpu/{module_file}"
DRIVER="fortran_gpu/{driver_file}"
FC="${{FC:-nvfortran}}"

# ── Détection automatique du GPU (cc80=A100, cc75=T4, cc70=V100) ─────────
detect_gpu_arch() {{
    GPU=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || echo "")
    case "$GPU" in
        *A100*)  echo "cc80" ;;
        *H100*)  echo "cc90" ;;
        *V100*)  echo "cc70" ;;
        *T4*)    echo "cc75" ;;
        *3090*|*3080*|*3070*) echo "cc86" ;;
        *)       echo "cc70" ;;   # fallback conservateur
    esac
}}

GPU_ARCH=$(detect_gpu_arch)
FFLAGS="-acc -gpu=${{GPU_ARCH}} -Minfo=accel -fast {cpp_flags}"

# ── Sanity checks ────────────────────────────────────────────────────────
if [ "$1" = "--check" ]; then
    echo "=== Environment check ==="
    which "$FC" && "$FC" --version | head -1 || echo "WARNING: $FC not found"
    GPU_NAME=$(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null || echo "GPU not found")
    echo "GPU  : $GPU_NAME"
    echo "Arch : $GPU_ARCH"
    echo "Files:"
    ls -lh fortran_gpu/*.f90 2>/dev/null || echo "  No .f90 files found"
    exit 0
fi

# ── Compile ──────────────────────────────────────────────────────────────
GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || echo "unknown")
echo "=== Compiling GPU Fortran ==="
echo "  GPU  : $GPU_NAME ($GPU_ARCH)"
echo "  Flags: $FC $FFLAGS"
echo ""

echo "  Step 1: Compile MODULE → module_kernels_gpu.o"
$FC $FFLAGS -c "$MODULE" -o module_kernels_gpu.o

echo "  Step 2: Compile DRIVER + link → $TARGET"
$FC $FFLAGS "$DRIVER" module_kernels_gpu.o -o "$TARGET"

echo ""
echo "=== SUCCESS: ./$TARGET ==="
echo "  Run  : ./$TARGET"
echo "  Watch: nvidia-smi dmon -d 1"
"""


def validation_agent(state: Phase1State) -> dict:
    """Génère Makefile + compile_gpu.sh, puis valide le code généré en 4 niveaux.

    Niveau 0 — gfortran local (toujours, 2 flavors) :
        Flavor 1 : compile sans !$acc (gfortran -O2 -fsyntax-only) → logique Fortran pure
        Flavor 2 : compile avec OpenACC (gfortran -fopenacc -fsyntax-only) → pragmas valides
    Niveau 1 — nvfortran local   : si nvfortran est dans le PATH
    Niveau 2 — compilation SSH   : si FORTRANSPIRE_GPU_HOST est défini dans l'env
    Niveau 3 — Génération seule  : toujours : Makefile + compile_gpu.sh pour lancement manuel
    """
    print(f"\n{SEP}")
    print("  [Validation] gfortran syntax check → GPU compilation")
    print(SEP)

    out_dir     = Path("output").resolve()
    gpu_dir     = out_dir / "fortran_gpu"
    log_lines:  List[str] = []
    compiled    = False

    # Determine filenames — prefer split module+driver, check both .f90 and .F90 (CPP)
    module_file = next(
        (f for f in ["module_kernels_gpu.F90", "module_kernels_gpu.f90",
                     "kernel_gpu.F90", "kernel_gpu.f90"]
         if (gpu_dir / f).exists()),
        "kernel_gpu.f90",
    )
    driver_file = next(
        (f for f in ["driver_gpu.F90", "driver_gpu.f90"]
         if (gpu_dir / f).exists()),
        "",
    )
    filepath    = state.get("fortran_filepath", "kernel")
    binary_name = Path(filepath).stem.lower().replace("-", "_") + "_gpu"

    # ── Always generate build artifacts ──────────────────────────────
    makefile_content = _make_makefile(out_dir, module_file, driver_file or module_file,
                                      binary_name, "")
    compile_sh       = _make_compile_script(out_dir, module_file, driver_file or module_file,
                                            binary_name,
                                            state.get("ast_info", {}).get("feature_flags"))
    _save(out_dir / "Makefile",         makefile_content)
    _save(out_dir / "compile_gpu.sh",   compile_sh)
    os.chmod(out_dir / "compile_gpu.sh", 0o755)
    log_lines.append("OK: Makefile and compile_gpu.sh generated in output/")
    print("  Generated: output/Makefile  +  output/compile_gpu.sh")

    # ── Level 0 : gfortran local syntax check (2 flavors) ────────────
    print(f"\n  [Level 0] gfortran local syntax check ...")
    sources_to_check: List[Path] = []
    if (gpu_dir / module_file).exists():
        sources_to_check.append(gpu_dir / module_file)
    if driver_file and (gpu_dir / driver_file).exists():
        sources_to_check.append(gpu_dir / driver_file)

    if sources_to_check:
        ok_no_acc, ok_with_acc, gfc_log = _gfortran_local_check(sources_to_check)
        log_lines.append("\n=== gfortran local check ===")
        log_lines.append(gfc_log)
        flavor1_status = "OK" if ok_no_acc   else "FAIL"
        flavor2_status = "OK" if ok_with_acc else "FAIL"
        print(f"  Flavor 1 (CPU, no !$acc pragmas) : {flavor1_status}")
        print(f"  Flavor 2 (gfortran -fopenacc)    : {flavor2_status}")
        if not ok_no_acc:
            print("  !! Fortran syntax errors — fix before GPU compilation")
        elif not ok_with_acc:
            print("  !! OpenACC directive errors (Fortran logic OK)")
    else:
        log_lines.append("SKIP (gfortran): source files not yet written")
        print("  Level 0 skipped: no source files found")

    # ── Build command list ────────────────────────────────────────────
    def _compile_cmds(fc: str) -> List[List[str]]:
        fflags = ["-acc", "-gpu=cc80", "-Minfo=accel", "-fast"]
        mod_src = str(gpu_dir / module_file)
        if driver_file and (gpu_dir / driver_file).exists():
            drv_src = str(gpu_dir / driver_file)
            return [
                [fc] + fflags + ["-c", mod_src, "-o", str(out_dir / "module_kernels_gpu.o")],
                [fc] + fflags + [drv_src, str(out_dir / "module_kernels_gpu.o"),
                                 "-o", str(out_dir / binary_name)],
            ]
        else:
            return [[fc] + fflags + [mod_src, "-o", str(out_dir / binary_name)]]

    def _run_cmds(cmds: List[List[str]], label: str) -> bool:
        for cmd in cmds:
            print(f"  $ {' '.join(cmd)}")
            try:
                r = subprocess.run(cmd, capture_output=True, text=True, timeout=180,
                                   cwd=str(out_dir))
                if r.returncode != 0:
                    log_lines.append(f"FAIL ({label}): {cmd[0]} rc={r.returncode}")
                    log_lines.append(r.stderr[:600])
                    print(f"  FAIL rc={r.returncode}: {r.stderr[:200]}")
                    return False
                if r.stdout:
                    log_lines.append(r.stdout[:300])
            except subprocess.TimeoutExpired:
                log_lines.append(f"FAIL ({label}): timeout >180s")
                return False
            except Exception as e:
                log_lines.append(f"FAIL ({label}): {e}")
                return False
        log_lines.append(f"OK ({label}): compiled → {binary_name}")
        return True

    # ── Level 1 : Local nvfortran ─────────────────────────────────────
    local_fc = _gpu_compiler()
    if local_fc and (gpu_dir / module_file).exists():
        print(f"\n  Attempting local compilation with {local_fc} ...")
        if _run_cmds(_compile_cmds(local_fc), "local"):
            compiled = True
            print(f"  LOCAL compilation OK → output/{binary_name}")
        else:
            print("  Local compilation failed — see validation.log")
    else:
        reason = "nvfortran not found" if not local_fc else f"{module_file} not found"
        log_lines.append(f"SKIP (local): {reason}")
        print(f"  Local compile skipped: {reason}")

    # ── Level 2 : SSH remote (any GPU node — OpenStack tenant, GENCI, on-prem) ───
    # Accept FORTRANSPIRE_GPU_* (preferred) or fall back to the legacy
    # AZURE_GPU_* names for users still on older config.
    gpu_host = os.getenv("FORTRANSPIRE_GPU_HOST") or os.getenv("AZURE_GPU_HOST", "")
    gpu_user = os.getenv("FORTRANSPIRE_GPU_USER") or os.getenv("AZURE_GPU_USER", "ubuntu")
    gpu_key  = os.getenv("FORTRANSPIRE_GPU_KEY")  or os.getenv("AZURE_GPU_KEY",  "")

    if not compiled and gpu_host:
        print(f"\n  Attempting remote compilation on {gpu_user}@{gpu_host} ...")
        ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "ConnectTimeout=15"]
        if gpu_key:
            ssh_opts += ["-i", gpu_key]

        remote_dir = f"~/gpu_agent_build/{binary_name}"
        try:
            # Copy output/ to remote
            scp_cmd = ["scp"] + ssh_opts + ["-r", str(out_dir),
                       f"{gpu_user}@{gpu_host}:{remote_dir}"]
            print(f"  scp output/ → {gpu_host}:{remote_dir}")
            r = subprocess.run(scp_cmd, capture_output=True, text=True, timeout=60)
            if r.returncode != 0:
                raise RuntimeError(f"scp failed: {r.stderr[:200]}")

            # Run make on remote
            make_cmd = ["ssh"] + ssh_opts + [f"{gpu_user}@{gpu_host}",
                        f"cd {remote_dir}/output && bash compile_gpu.sh"]
            print(f"  ssh → bash compile_gpu.sh")
            r = subprocess.run(make_cmd, capture_output=True, text=True, timeout=180)
            if r.returncode == 0:
                compiled = True
                log_lines.append(f"OK (SSH {gpu_host}): compiled → {binary_name}")
                print(f"  REMOTE compilation OK on {gpu_host}")
                print(f"  Binary: {remote_dir}/output/{binary_name}")
            else:
                log_lines.append(f"FAIL (SSH): rc={r.returncode}\n{r.stderr[:400]}")
                print(f"  Remote compilation failed: {r.stderr[:200]}")
        except Exception as e:
            log_lines.append(f"FAIL (SSH): {e}")
            print(f"  SSH error: {e}")
    elif not compiled and not gpu_host:
        log_lines.append(
            "SKIP (SSH): set FORTRANSPIRE_GPU_HOST=<ip> "
            "(+ FORTRANSPIRE_GPU_USER, FORTRANSPIRE_GPU_KEY) to enable "
            "remote compilation"
        )
        print("  SSH skipped: FORTRANSPIRE_GPU_HOST not set")

    # ── Level 3 : Manual instructions ────────────────────────────────
    if not compiled:
        log_lines.append("")
        log_lines.append("=== Manual compilation (copy output/ to GPU node) ===")
        log_lines.append(f"  rsync -a output/ user@<gpu-host>:~/build/")
        log_lines.append(f"  ssh user@<gpu-host>")
        log_lines.append(f"  cd ~/build && bash compile_gpu.sh")
        log_lines.append(f"  ./{binary_name}")
        print("\n  Manual steps written to validation.log")

    # ── Report ────────────────────────────────────────────────────────
    log = "\n".join(log_lines)
    _save(gpu_dir / "validation.log", log)

    print(f"\n  Files generated in output/:")
    for f in sorted(out_dir.rglob("*")):
        if f.is_file() and not f.name.endswith(".pyc"):
            size = f.stat().st_size
            rel  = f.relative_to(out_dir)
            ok   = "OK" if size > 50 else "??"
            print(f"    [{ok}] {str(rel):<45} {size:>7} bytes")

    status = "COMPILED" if compiled else "ARTIFACTS_READY (run compile_gpu.sh on GPU node)"
    print(f"\n  Status : {status}")
    print(SEP2 + "\n")

    return {
        "validation_passed": compiled,
        "validation_log":    log,
        "executed_agents":   list(state.get("executed_agents", [])) + ["validation"],
    }
