! OpenACC variant of wave_kernels — hand-written for the equivalence test
! suite, NOT generated by `fortranspire gpu`. We bake this in so the CI
! check does not require an LLM endpoint; an end-to-end LLM-generation
! test belongs in a separate `pytest -m llm` job (see #45).
!
! Structurally identical to original.f90 with `!$acc parallel loop`
! directives + `private(i, j)`. The loop bounds, intent, and operations
! are byte-identical to original.f90 — the only changes are pragmas.
!
! `gfortran -fopenacc` accepts these directives but does not actually
! offload to a GPU; it parallelises across CPU threads via OpenMP. That
! is enough to validate the *correctness* of the OpenACC port — the
! arithmetic is identical to the serial path, only the parallel
! schedule changes.

module wave_kernels
  implicit none

contains

  subroutine update_vx(vx, sigma_xx, dx, nx, ny)
    real(8), intent(inout) :: vx(nx, ny)
    real(8), intent(in)    :: sigma_xx(nx, ny)
    real(8), intent(in)    :: dx
    integer, intent(in)    :: nx, ny
    integer :: i, j
    !$acc parallel loop collapse(2) private(i, j) default(present)
    do j = 2, ny
      do i = 2, nx
        vx(i, j) = vx(i, j) + (sigma_xx(i, j) - sigma_xx(i-1, j)) / dx
      end do
    end do
    !$acc end parallel loop
  end subroutine update_vx

  subroutine update_sigma(sigma_xx, vx, vy, dx, dy, nx, ny)
    real(8), intent(inout) :: sigma_xx(nx, ny)
    real(8), intent(in)    :: vx(nx, ny), vy(nx, ny)
    real(8), intent(in)    :: dx, dy
    integer, intent(in)    :: nx, ny
    integer :: i, j
    !$acc parallel loop collapse(2) private(i, j) default(present)
    do j = 2, ny - 1
      do i = 2, nx - 1
        sigma_xx(i, j) = sigma_xx(i, j) &
          + (vx(i+1, j) - vx(i, j)) / dx &
          + (vy(i, j+1) - vy(i, j)) / dy
      end do
    end do
    !$acc end parallel loop
  end subroutine update_sigma

end module wave_kernels
